<?php

namespace Database\Seeders;

use App\Models\Sydney;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SecondSydneySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $results = [
            [
                'date' => '2024-08-29',
                'day' => 'kamis',
                'first_result' => '3711',
                'second_result' => '8423',
                'third_result' => '1135',
            ],
            [
                'date' => '2024-08-28',
                'day' => 'rabu',
                'first_result' => '4185',
                'second_result' => '1959',
                'third_result' => '8755',
            ],
            [
                'date' => '2024-08-27',
                'day' => 'selasa',
                'first_result' => '6178',
                'second_result' => '1672',
                'third_result' => '4001',
            ],
            [
                'date' => '2024-08-26',
                'day' => 'senin',
                'first_result' => '1913',
                'second_result' => '1747',
                'third_result' => '2508',
            ],
            [
                'date' => '2024-08-25',
                'day' => 'minggu',
                'first_result' => '6876',
                'second_result' => '7411',
                'third_result' => '0932',
            ],
            [
                'date' => '2024-08-24',
                'day' => 'sabtu',
                'first_result' => '5097',
                'second_result' => '1930',
                'third_result' => '4676',
            ],
            [
                'date' => '2024-08-23',
                'day' => 'jumat',
                'first_result' => '7581',
                'second_result' => '7767',
                'third_result' => '2765',
            ],
            [
                'date' => '2024-08-22',
                'day' => 'kamis',
                'first_result' => '0658',
                'second_result' => '1658',
                'third_result' => '9040',
            ],
            [
                'date' => '2024-08-21',
                'day' => 'rabu',
                'first_result' => '1390',
                'second_result' => '1401',
                'third_result' => '3904',
            ],
            [
                'date' => '2024-08-20',
                'day' => 'selasa',
                'first_result' => '2562',
                'second_result' => '9115',
                'third_result' => '7368',
            ],
            [
                'date' => '2024-08-19',
                'day' => 'senin',
                'first_result' => '8306',
                'second_result' => '4359',
                'third_result' => '8466',
            ],
            [
                'date' => '2024-08-18',
                'day' => 'minggu',
                'first_result' => '6528',
                'second_result' => '6159',
                'third_result' => '4432',
            ],
            [
                'date' => '2024-08-17',
                'day' => 'sabtu',
                'first_result' => '0159',
                'second_result' => '4113',
                'third_result' => '5117',
            ],
            [
                'date' => '2024-08-16',
                'day' => 'jumat',
                'first_result' => '4292',
                'second_result' => '7167',
                'third_result' => '4893',
            ],
            [
                'date' => '2024-08-15',
                'day' => 'kamis',
                'first_result' => '8306',
                'second_result' => '4359',
                'third_result' => '8466',
            ],
            [
                'date' => '2024-08-14',
                'day' => 'rabu',
                'first_result' => '6512',
                'second_result' => '1690',
                'third_result' => '8710',
            ],
            [
                'date' => '2024-08-13',
                'day' => 'selasa',
                'first_result' => '5460',
                'second_result' => '4758',
                'third_result' => '0375',
            ],
            [
                'date' => '2024-08-12',
                'day' => 'senin',
                'first_result' => '8618',
                'second_result' => '9723',
                'third_result' => '2550',
            ],
            [
                'date' => '2024-08-11',
                'day' => 'minggu',
                'first_result' => '4091',
                'second_result' => '8345',
                'third_result' => '5704',
            ],
            [
                'date' => '2024-08-10',
                'day' => 'sabtu',
                'first_result' => '6192',
                'second_result' => '6970',
                'third_result' => '8044',
            ],
            [
                'date' => '2024-08-09',
                'day' => 'jumat',
                'first_result' => '0365',
                'second_result' => '1546',
                'third_result' => '1662',
            ],
            [
                'date' => '2024-08-08',
                'day' => 'kamis',
                'first_result' => '3985',
                'second_result' => '7821',
                'third_result' => '9958',
            ],
            [
                'date' => '2024-08-07',
                'day' => 'rabu',
                'first_result' => '1719',
                'second_result' => '3054',
                'third_result' => '1697',
            ],
            [
                'date' => '2024-08-06',
                'day' => 'selasa',
                'first_result' => '9884',
                'second_result' => '2281',
                'third_result' => '0930',
            ],
            [
                'date' => '2024-08-05',
                'day' => 'senin',
                'first_result' => '2650',
                'second_result' => '0824',
                'third_result' => '6247',
            ],
            [
                'date' => '2024-08-04',
                'day' => 'minggu',
                'first_result' => '7495',
                'second_result' => '9919',
                'third_result' => '6360',
            ],
            [
                'date' => '2024-08-03',
                'day' => 'sabtu',
                'first_result' => '0339',
                'second_result' => '3434',
                'third_result' => '9513',
            ],
            [
                'date' => '2024-08-02',
                'day' => 'jumat',
                'first_result' => '5488',
                'second_result' => '5796',
                'third_result' => '7043',
            ],
            [
                'date' => '2024-08-01',
                'day' => 'kamis',
                'first_result' => '4753',
                'second_result' => '3891',
                'third_result' => '7997',
            ],
            [
                'date' => '2024-07-31',
                'day' => 'rabu',
                'first_result' => '1574',
                'second_result' => '1945',
                'third_result' => '6443',
            ],
            [
                'date' => '2024-07-30',
                'day' => 'selasa',
                'first_result' => '4152',
                'second_result' => '7311',
                'third_result' => '2938',
            ],
            [
                'date' => '2024-07-29',
                'day' => 'senin',
                'first_result' => '8977',
                'second_result' => '9146',
                'third_result' => '5348',
            ],
            [
                'date' => '2024-07-28',
                'day' => 'minggu',
                'first_result' => '2704',
                'second_result' => '6470',
                'third_result' => '5379',
            ],
            [
                'date' => '2024-07-27',
                'day' => 'sabtu',
                'first_result' => '7847',
                'second_result' => '0237',
                'third_result' => '2685',
            ],
            [
                'date' => '2024-07-26',
                'day' => 'jumat',
                'first_result' => '3519',
                'second_result' => '3214',
                'third_result' => '0336',
            ],
            [
                'date' => '2024-07-25',
                'day' => 'kamis',
                'first_result' => '8395',
                'second_result' => '7173',
                'third_result' => '3555',
            ],
            [
                'date' => '2024-07-24',
                'day' => 'rabu',
                'first_result' => '4786',
                'second_result' => '1178',
                'third_result' => '9819',
            ],
            [
                'date' => '2024-07-23',
                'day' => 'selasa',
                'first_result' => '8123',
                'second_result' => '1781',
                'third_result' => '0464',
            ],
            [
                'date' => '2024-07-22',
                'day' => 'senin',
                'first_result' => '0989',
                'second_result' => '8564',
                'third_result' => '4818',
            ],
            [
                'date' => '2024-07-21',
                'day' => 'minggu',
                'first_result' => '4478',
                'second_result' => '2170',
                'third_result' => '1446',
            ],
            [
                'date' => '2024-07-20',
                'day' => 'sabtu',
                'first_result' => '2267',
                'second_result' => '8462',
                'third_result' => '0243',
            ],
            [
                'date' => '2024-07-19',
                'day' => 'jumat',
                'first_result' => '5434',
                'second_result' => '5736',
                'third_result' => '7625',
            ],
            [
                'date' => '2024-07-18',
                'day' => 'kamis',
                'first_result' => '7335',
                'second_result' => '0174',
                'third_result' => '2497',
            ],
            [
                'date' => '2024-07-17',
                'day' => 'rabu',
                'first_result' => '8812',
                'second_result' => '7135',
                'third_result' => '9762',
            ],
            [
                'date' => '2024-07-16',
                'day' => 'selasa',
                'first_result' => '2067',
                'second_result' => '3359',
                'third_result' => '3590',
            ],
            [
                'date' => '2024-07-15',
                'day' => 'senin',
                'first_result' => '9930',
                'second_result' => '3274',
                'third_result' => '0134',
            ],
            [
                'date' => '2024-07-14',
                'day' => 'minggu',
                'first_result' => '5109',
                'second_result' => '5281',
                'third_result' => '8408',
            ],
            [
                'date' => '2024-07-13',
                'day' => 'sabtu',
                'first_result' => '4225',
                'second_result' => '0783',
                'third_result' => '9771',
            ],
            [
                'date' => '2024-07-12',
                'day' => 'jumat',
                'first_result' => '8074',
                'second_result' => '8825',
                'third_result' => '3196',
            ],
            [
                'date' => '2024-07-11',
                'day' => 'kamis',
                'first_result' => '0181',
                'second_result' => '3595',
                'third_result' => '8727',
            ],
            [
                'date' => '2024-07-10',
                'day' => 'rabu',
                'first_result' => '7853',
                'second_result' => '7678',
                'third_result' => '6109',
            ],
            [
                'date' => '2024-07-09',
                'day' => 'selasa',
                'first_result' => '6726',
                'second_result' => '8036',
                'third_result' => '0789',
            ],
            [
                'date' => '2024-07-08',
                'day' => 'senin',
                'first_result' => '9070',
                'second_result' => '9428',
                'third_result' => '8205',
            ],
            [
                'date' => '2024-07-07',
                'day' => 'minggu',
                'first_result' => '0389',
                'second_result' => '8209',
                'third_result' => '3453',
            ],
            [
                'date' => '2024-07-06',
                'day' => 'sabtu',
                'first_result' => '4863',
                'second_result' => '1090',
                'third_result' => '4536',
            ],
            [
                'date' => '2024-07-05',
                'day' => 'jumat',
                'first_result' => '5613',
                'second_result' => '0046',
                'third_result' => '0810',
            ],
            [
                'date' => '2024-07-04',
                'day' => 'kamis',
                'first_result' => '2446',
                'second_result' => '6749',
                'third_result' => '0435',
            ],
            [
                'date' => '2024-07-03',
                'day' => 'rabu',
                'first_result' => '7061',
                'second_result' => '9075',
                'third_result' => '5798',
            ],
            [
                'date' => '2024-07-02',
                'day' => 'selasa',
                'first_result' => '1505',
                'second_result' => '4775',
                'third_result' => '2625',
            ],
            [
                'date' => '2024-07-01',
                'day' => 'senin',
                'first_result' => '8837',
                'second_result' => '1195',
                'third_result' => '3652',
            ],
        ];


        foreach($results as $result) {
            Sydney::create($result);
        }
    }
}
